{{- if .Values.clusterissuers -}}
{{- $fullName := include "cert-manager-configs.fullname" . -}}

{{- $root := . }}
{{- range $clusterissuer := .Values.clusterissuers }}
---
apiVersion: certmanager.k8s.io/v1alpha1
kind: ClusterIssuer
metadata:
  name: {{ $clusterissuer.name }}
  labels:
    app: {{ template "cert-manager-configs.name" $root }}
    chart: {{ template "cert-manager-configs.chart" $root }}
    release: {{ $root.Release.Name }}
    heritage: {{ $root.Release.Service }}
spec:
  acme:
    # The ACME server URL
    server: {{ $clusterissuer.server }}
    # Email address used for ACME registration
    email: {{ $clusterissuer.email }}
    # Name of a secret used to store the ACME account private key
    privateKeySecretRef:
      name: {{ $clusterissuer.name }}
    # Enable the Route53 Challenge Provider which uses Ambient Credentials
{{ toYaml $clusterissuer.challengeproviders | indent 4 }}
{{- end }}

{{- end }}
