{{- if .Values.curator.enabled -}}
apiVersion: batch/v2alpha1
kind: CronJob
metadata:
  name: {{ template "elasticsearch.fullname" . }}-curator
  labels:
    app: {{ template "elasticsearch.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    component: curator
spec:
  schedule: {{ .Values.curator.schedule | quote }}
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 3
  concurrencyPolicy: Forbid
  startingDeadlineSeconds: 120
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: {{ template "elasticsearch.fullname" . }}-curator
              image: "{{ .Values.curator.image }}:{{ .Values.curator.imageTag }}"
              imagePullPolicy: {{ .Values.curator.imagePullPolicy }}
              args:
                - "--config"
                - "/etc/config/config.yml"
                - "/etc/config/action_file.yml"
              volumeMounts:
                - name: config-volume
                  mountPath: /etc/config
          volumes:
            - name: config-volume
              configMap:
                name: {{ template "elasticsearch.fullname" . }}-curator-config
          restartPolicy: {{ .Values.curator.restartPolicy }}
{{- end -}}
