apiVersion: v1
kind: Service
metadata:
  name: {{ template "metrics-server.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
{{ include "metrics-server.labels" . | indent 4 }}
    kubernetes.io/name: "Metrics-server"
spec:
  ports:
  - port: {{ .Values.service.port }}
    protocol: TCP
    targetPort: {{ .Values.service.targetPort }}
  selector:
    app: {{ template "metrics-server.fullname" . }}
