---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ template "hackmd.fullname" . }}
  labels:
    app: {{ template "hackmd.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
data:
  config.json: |
    {
        "production": {
            "urladdport": true,
            "email": true,
            "db": {
                "username": "{{ .Values.postgresql.postgresUser }}",
                "password": "{{ .Values.postgresql.postgresPassword }}",
                "database": "{{ .Values.postgresql.postgresDatabase }}",
                "host": "{{ template "postgresql.fullname" . }}",
                "port": "5432",
                "dialect": "postgres"
            }
        }
    }
  .sequelizerc: |
    var path = require('path');
    module.exports = {
        'config':          path.resolve('config.json'),
        'migrations-path': path.resolve('lib', 'migrations'),
        'models-path':     path.resolve('lib', 'models'),
        'url':             process.env.HMD_DB_URL
    }
