apiVersion: v1
kind: Service
metadata:
  name: {{ template "kafka.fullname" . }}-headless
  labels:
    app: {{ template "kafka.name" . }}
    chart: {{ template "kafka.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
  annotations:
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  clusterIP: None
  ports:
{{- range $key, $port := .Values.ports }}
    - name: {{ $key }}
      port: {{ $port.containerPort }}
      targetPort: {{ $port.name }}
      protocol: {{ $port.protocol }}
{{- end }}
  selector:
    app: {{ template "kafka.name" . }}
    release: {{ .Release.Name }}
