# Default values for elasticsearch.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
appVersion: "5.4"

image:
  repository: "docker.elastic.co/elasticsearch/elasticsearch-oss"
  tag: "6.2.2"
  pullPolicy: "IfNotPresent"

cluster:
  name: "elasticsearch"
  kubernetesDomain: cluster.local
  # If you want X-Pack installed, switch to an image that includes it, enable this option and toggle the features you want
  # enabled in the environment variables outlined in the README
  xpackEnable: false
  config:
  env:
    # IMPORTANT: https://www.elastic.co/guide/en/elasticsearch/reference/current/important-settings.html#minimum_master_nodes
    # To prevent data loss, it is vital to configure the discovery.zen.minimum_master_nodes setting so that each master-eligible
    # node knows the minimum number of master-eligible nodes that must be visible in order to form a cluster.
    MINIMUM_MASTER_NODES: "2"

client:
  name: client
  replicas: 2
  serviceType: ClusterIP

## (dict) If specified, apply these annotations to the client service
#  serviceAnnotations:
#    example: client-svc-foo

  heapSize: "1024m"
  antiAffinity: "hard"
  resources:
    limits:
      cpu: "1"
      memory: "1280Mi"
    requests:
      cpu: "25m"
      memory: "1152Mi"

  ## (dict) If specified, apply these annotations to each client Pod
  # podAnnotations:
  #   example: client-foo

master:
  name: master
  exposeHttp: false
  replicas: 3
  heapSize: "1024m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "4Gi"
    storageClass: "default"
  antiAffinity: "hard"
  resources:
    limits:
      cpu: "1"
      memory: "1280Mi"
    requests:
      cpu: "25m"
      memory: "1152Mi"

  ## (dict) If specified, apply these annotations to each master Pod
  # podAnnotations:
  #   example: master-foo

data:
  name: data
  exposeHttp: false
  replicas: 2
  heapSize: "1536m"
  persistence:
    enabled: true
    accessMode: ReadWriteOnce
    name: data
    size: "30Gi"
    storageClass: "default"
  terminationGracePeriodSeconds: 3600
  antiAffinity: "hard"
  resources:
    limits:
      cpu: "1"
      memory: "2048Mi"
    requests:
      cpu: "25m"
      memory: "1792Mi"
  ## (dict) If specified, apply these annotations to each data Pod
  # podAnnotations:
  #   example: data-foo

curator:
  enabled: true
  image: bobrik/curator
  imageTag: "5.4.0"
  imagePullPolicy: IfNotPresent
  restartPolicy: Never
  schedule: "0 1 * * *"
  # Allows modification of the default age-based filter. If you require more
  # sophisticated filtering, modify the action file specified in
  # templates/es-curator-config.yaml.
  age:
    timestring: "%Y.%m.%d"
    unit: "days"
    unitCount: 3
